version: "3.8"

services:
  php-73:
    container_name: "php-73-alias1"
    image: "seffeng/php:7.3"
    networks:
      network-01:
        aliases:
          - php-73-net1
    #extra_hosts:
    #  - "localhost:127.0.0.1"
    volumes:
      - "/opt/websrv/data/wwwroot:/opt/websrv/data/wwwroot"
      - "/opt/websrv/tmp:/opt/websrv/tmp"
      - "/opt/websrv/logs/php/7.3:/opt/websrv/logs"

  php-74:
    container_name: "php-74-alias1"
    image: "seffeng/php:7.4"
    networks:
      network-01:
        aliases:
          - php-74-net1
    #extra_hosts:
    #  - "localhost:127.0.0.1"
    volumes:
      - "/opt/websrv/data/wwwroot:/opt/websrv/data/wwwroot"
      - "/opt/websrv/tmp:/opt/websrv/tmp"
      - "/opt/websrv/logs/php/7.4:/opt/websrv/logs"

  php-80:
    container_name: "php-80-alias1"
    image: "seffeng/php"
    networks:
      network-01:
        aliases:
          - php-80-net1
    #extra_hosts:
    #  - "localhost:127.0.0.1"
    volumes:
      - "/opt/websrv/data/wwwroot:/opt/websrv/data/wwwroot"
      - "/opt/websrv/tmp:/opt/websrv/tmp"
      - "/opt/websrv/logs/php/8.0:/opt/websrv/logs"

networks:
  network-01:
    driver: bridge
    name: network-01